[project]
name = "tiptap-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "air>=0.30.0",
    "fastapi[standard]>=0.120.1",
    "sqlmodel>=0.0.27",
]
