[project]
name = "clerk-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "air>=0.30.0",
    "clerk-backend-api>=3.3.1",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.119.1",
    "httpx>=0.28.1",
]
