list:
    just -l

# Runs the main app to port 8000
run:
    echo "HELLO WORLD"
    uv run python main.py

# list issues given repo org and name
list-issue ORG REPO:
    uv run python scripts/list_issues.py {{ORG}} {{REPO}}

